[versions]
agp = "8.1.4"
koinAndroid = "4.0.0"
kotlin = "1.9.21"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.2.0"
navigationFragmentKtx = "2.8.3"
navigationUiKtx = "2.8.3"
daggerVersion = "2.51.1"
androidxLifecyleVersion = '2.8.7'
androidxRoomVersion = '2.6.1'
gsonVersion = '2.10.1'
okhttpVersion = '4.12.0'
retrofitVersion = '2.11.0'
rxJavaVersion = '2.2.21'
rxAndroidVersion = '2.1.1'
rxKotlinVersion = '2.4.0'
recyclerviewVersion = '1.3.2'
picassoVersion = '2.71828'
picassoOkHttpVersion = '1.1.0'
lottieVersion = '5.2.0'

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinAndroid" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinAndroid" }
koin-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koinAndroid" }

# androidx
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerviewVersion" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }

androidx-lifecycle-compiler = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "androidxLifecyleVersion" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecyleVersion" }

# room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoomVersion" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoomVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoomVersion" }
androidx-room-rxjava2 = { group = "androidx.room", name = "room-rxjava2", version.ref = "androidxRoomVersion" }

# google
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gsonVersion" }

# square
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp3", version.ref = "okhttpVersion" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpVersion" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
retrofit2-adapter-rxjava2 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "retrofitVersion" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofitVersion" }

# rx
rxjava = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rxJavaVersion" }
rxandroid = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rxAndroidVersion" }
rxkotlin = { group = "io.reactivex.rxjava2", name = "rxkotlin", version.ref = "rxKotlinVersion" }

# ui
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
picasso = { group = "com.squareup.picasso", name = "picasso", version.ref = "picassoVersion" }
picassoOkHttp = { group = "com.jakewharton.picasso", name = "picasso2-okhttp3-downloader", version.ref = "picassoOkHttpVersion" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottieVersion" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
